#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  printf 'Usage: %s [-o output.html]\n' "${0##*/}" >&2
}

html_escape() {
  sed \
    -e 's/&/\&amp;/g' \
    -e 's/</\&lt;/g' \
    -e 's/>/\&gt;/g' \
    -e 's/"/\&quot;/g' \
    -e "s/'/\&#39;/g"
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

run_section() {
  local title=$1
  local escaped_title
  shift

  escaped_title=$(printf '%s' "$title" | html_escape)
  printf '<section>\n<h2>%s</h2>\n<pre>\n' "$escaped_title"
  if "$@" 2>&1 | html_escape; then
    :
  else
    printf 'Command failed: %s\n' "$*" | html_escape
  fi
  printf '</pre>\n</section>\n'
}

system_summary() {
  printf 'Generated: %s\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"
  printf 'Hostname:  %s\n' "$(hostname)"
  printf 'Kernel:    %s\n' "$(uname -srmo)"
  printf 'Uptime:    %s\n' "$(uptime -p 2>/dev/null || uptime)"
  printf 'User:      %s\n' "${USER:-unknown}"
}

os_release() {
  if [[ -r /etc/os-release ]]; then
    awk -F= '
      $1 == "PRETTY_NAME" {
        gsub(/^"|"$/, "", $2)
        print $2
      }
    ' /etc/os-release
  else
    printf 'OS release information unavailable\n'
  fi
}

cpu_summary() {
  if [[ -r /proc/cpuinfo ]]; then
    awk -F: '
      $1 ~ /^model name/ && !model { sub(/^ /, "", $2); model=$2 }
      $1 ~ /^processor/ { count++ }
      END {
        printf "CPU model: %s\n", model ? model : "unknown"
        printf "CPU cores: %d\n", count ? count : 0
      }
    ' /proc/cpuinfo
  else
    printf 'CPU information unavailable\n'
  fi
}

memory_summary() {
  if command_exists free; then
    free -h
  elif [[ -r /proc/meminfo ]]; then
    awk '/MemTotal|MemAvailable|SwapTotal|SwapFree/ { print }' /proc/meminfo
  else
    printf 'Memory information unavailable\n'
  fi
}

disk_summary() {
  if command_exists df; then
    df -hT -x tmpfs -x devtmpfs
  else
    printf 'Disk usage information unavailable\n'
  fi
}

network_summary() {
  if command_exists ip; then
    ip -brief address
  else
    hostname -I 2>/dev/null || printf 'Network address information unavailable\n'
  fi
}

socket_summary() {
  if command_exists ss; then
    ss -tulpen
  else
    printf 'Socket summary unavailable: ss is not installed\n'
  fi
}

process_summary() {
  ps -eo pid,ppid,user,stat,%cpu,%mem,comm --sort=-%cpu | head -n 16
}

login_summary() {
  who 2>/dev/null || printf 'Login information unavailable\n'
}

write_report() {
  local output=$1
  local tmp
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' RETURN

  {
    cat <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>System Status Report</title>
<style>
:root {
  color-scheme: light dark;
  --bg: #f7f8fa;
  --fg: #1d232a;
  --muted: #586474;
  --panel: #ffffff;
  --border: #cfd6df;
  --accent: #176b87;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #101418;
    --fg: #e7ebef;
    --muted: #aab4c0;
    --panel: #171d23;
    --border: #303943;
    --accent: #5fb3ce;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  font: 15px/1.45 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
main {
  max-width: 1120px;
  margin: 0 auto;
  padding: 32px 20px;
}
header {
  border-bottom: 3px solid var(--accent);
  margin-bottom: 22px;
  padding-bottom: 14px;
}
h1 {
  font-size: 2rem;
  margin: 0 0 4px;
}
.subtitle {
  color: var(--muted);
  margin: 0;
}
section {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  margin: 18px 0;
  overflow: hidden;
}
h2 {
  border-bottom: 1px solid var(--border);
  font-size: 1.05rem;
  margin: 0;
  padding: 12px 14px;
}
pre {
  margin: 0;
  overflow-x: auto;
  padding: 14px;
  white-space: pre;
}
footer {
  color: var(--muted);
  font-size: .9rem;
  margin-top: 24px;
}
</style>
</head>
<body>
<main>
<header>
<h1>System Status Report</h1>
<p class="subtitle">Generated by Bash from local system status commands.</p>
</header>
HTML
    run_section "System Summary" system_summary
    run_section "Operating System" os_release
    run_section "CPU" cpu_summary
    run_section "Memory" memory_summary
    run_section "Disk Usage" disk_summary
    run_section "Network Addresses" network_summary
    run_section "Listening Sockets" socket_summary
    run_section "Top CPU Processes" process_summary
    run_section "Logged-In Users" login_summary
    cat <<'HTML'
<footer>Report content reflects command output at generation time.</footer>
</main>
</body>
</html>
HTML
  } >"$tmp"

  mv "$tmp" "$output"
  chmod u=rw,go=r "$output"
  trap - RETURN
}

main() {
  local output=report.html

  while getopts ':ho:' opt; do
    case "$opt" in
      h)
        usage
        return 0
        ;;
      o)
        output=$OPTARG
        ;;
      :)
        printf 'Option -%s requires an argument.\n' "$OPTARG" >&2
        usage
        return 2
        ;;
      \?)
        printf 'Unknown option: -%s\n' "$OPTARG" >&2
        usage
        return 2
        ;;
    esac
  done
  shift "$((OPTIND - 1))"

  if (($# > 0)); then
    usage
    return 2
  fi

  write_report "$output"
  printf 'Wrote %s\n' "$output"
}

main "$@"
